/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['var(--font-interface)'],
        display: ['var(--font-display)'],
        mono: ['var(--font-science)'],
      },
      colors: {
        gray: {
          50: 'rgb(var(--surface-raised) / <alpha-value>)',
          100: 'rgb(var(--surface) / <alpha-value>)',
          200: 'rgb(var(--border) / <alpha-value>)',
          300: 'rgb(var(--border-strong) / <alpha-value>)',
          400: 'rgb(var(--text-tertiary) / <alpha-value>)',
          500: 'rgb(var(--text-secondary) / <alpha-value>)',
          600: 'rgb(var(--text-secondary) / <alpha-value>)',
          700: 'rgb(var(--text-primary) / <alpha-value>)',
          800: 'rgb(var(--surface) / <alpha-value>)',
          900: 'rgb(var(--text-primary) / <alpha-value>)',
        },
        blue: {
          50: 'rgb(var(--primary-light) / <alpha-value>)',
          100: 'rgb(var(--primary-light) / <alpha-value>)',
          200: 'rgb(var(--primary) / <alpha-value>)',
          300: 'rgb(var(--primary) / <alpha-value>)',
          400: 'rgb(var(--primary) / <alpha-value>)',
          500: 'rgb(var(--primary) / <alpha-value>)',
          600: 'rgb(var(--primary) / <alpha-value>)',
          700: 'rgb(var(--primary-dark) / <alpha-value>)',
          800: 'rgb(var(--primary-dark) / <alpha-value>)',
          900: 'rgb(var(--primary-light) / <alpha-value>)',
        },
        green: {
          50: 'rgb(var(--primary-light) / <alpha-value>)',
          100: 'rgb(var(--primary-light) / <alpha-value>)',
          200: 'rgb(var(--success) / <alpha-value>)',
          300: 'rgb(var(--success) / <alpha-value>)',
          400: 'rgb(var(--success) / <alpha-value>)',
          500: 'rgb(var(--success) / <alpha-value>)',
          600: 'rgb(var(--success) / <alpha-value>)',
          700: 'rgb(var(--primary-dark) / <alpha-value>)',
          800: 'rgb(var(--primary-dark) / <alpha-value>)',
          900: 'rgb(var(--primary-light) / <alpha-value>)',
        },
        amber: {
          50: 'rgb(var(--energy-light) / <alpha-value>)',
          100: 'rgb(var(--energy-light) / <alpha-value>)',
          200: 'rgb(var(--energy) / <alpha-value>)',
          300: 'rgb(var(--energy) / <alpha-value>)',
          400: 'rgb(var(--energy) / <alpha-value>)',
          500: 'rgb(var(--energy) / <alpha-value>)',
          600: 'rgb(var(--energy) / <alpha-value>)',
          700: 'rgb(var(--warning) / <alpha-value>)',
          800: 'rgb(var(--warning) / <alpha-value>)',
          900: 'rgb(var(--energy-light) / <alpha-value>)',
        },
        red: {
          50: 'rgb(var(--reaction-light) / <alpha-value>)',
          100: 'rgb(var(--reaction-light) / <alpha-value>)',
          200: 'rgb(var(--error) / <alpha-value>)',
          300: 'rgb(var(--error) / <alpha-value>)',
          400: 'rgb(var(--error) / <alpha-value>)',
          500: 'rgb(var(--error) / <alpha-value>)',
          600: 'rgb(var(--error) / <alpha-value>)',
          700: 'rgb(var(--reaction) / <alpha-value>)',
          800: 'rgb(var(--reaction) / <alpha-value>)',
          900: 'rgb(var(--reaction-light) / <alpha-value>)',
        },
        white: 'rgb(var(--on-primary) / <alpha-value>)',
      },
    },
  },
  plugins: [],
}
